=== DarkHesse/EdictsAshoka/ashoka_edicts.dtd
<!ELEMENT edicts (edict+)>
<!ELEMENT edict (head,sentence+)>
<!ELEMENT head (source, num, place)>
<!ELEMENT source (#PCDATA)>
<!ELEMENT num (#PCDATA)>
<!ELEMENT place (#PCDATA)>
<!ELEMENT sentence (number+,text+)>
<!ELEMENT number (#PCDATA)>
<!ELEMENT text (#PCDATA)>

=== DarkHesse/EdictsAshoka/ashoka_edicts.xml
<?xml version="1.1" encoding="UTF-8"?>


<!DOCTYPE edicts SYSTEM "ashoka_edicts.dtd">
<edicts>
    <head>
        <source>text</source>
        <place>text</place>
    </head>
    <content>
        <sentence>
            <number>a</number>
            <text>text</text>
        </sentence>
    </content>
</edicts>
